In [36]:
import pandas as pd 

import torch
import torch.nn as nn 
import torchvision as tv 
import torch.nn.functional as F

import numpy as np
import matplotlib.pyplot as plt
import cv2
import os

from tqdm import tqdm

import pandas as pd

In [2]:
train = pd.read_csv('/content/train.csv')
X_test = pd.read_csv('/content/test.csv')

train.fillna(0, inplace = True)
X_test.fillna(0 , inplace= True)

In [3]:
from sklearn. preprocessing import OneHotEncoder

y_train = train['Transported']
X_train = train.drop(columns = ['Transported'],axis = 1)


name = X_train['Name']
X_train = X_train.drop( columns = ['Name'] , axis = 1 )

In [4]:

from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()

In [5]:

name = name.astype('str')

In [6]:
name = labelencoder.fit_transform(name)

In [7]:
name_df = pd.DataFrame(name)
#rename

In [8]:
passengers = []
ids = []

Pass_id_dict = {}
for i in X_train.PassengerId :
  split_i = i.split('_')
  split_i[1] = int(split_i[1])
  
  passengers.append(split_i[0])
  ids.append(split_i[1])
  

 

#X_train.loc[X_train['PassengerId']. isin(Pass_id_dict.keys())]
  
X_train['Group'] = passengers
X_train['Number_in_group'] = ids

In [9]:
X_train = X_train.drop( columns = ['PassengerId'] , axis = 1 )

In [10]:
import numpy as np

deck =[]
num=[]
side=[]

for i in X_train.Cabin :
  if i != 0 :
    
    split_i = i.split('/')
    deck.append(split_i[0])
    num.append(int(split_i[1]))
    side.append(split_i[2])
  if i == 0 :
    deck.append(0)
    num.append(0)
    side.append(0)



  
X_train['Deck'] = deck
X_train['Num'] = num
X_train['Side'] = side
X_train = X_train.drop( columns = ['Cabin' ] , axis = 1 )

categorical = X_train[['HomePlanet' , 'Destination'  , 'Deck' , 'Side' ]]
categorical = pd.get_dummies(categorical)




numerical = X_train[['CryoSleep' , 'Age' , 'VIP' , 'RoomService' , 'FoodCourt' , 'ShoppingMall' , 'Spa' , 'VRDeck' , 'Group' , 'Number_in_group' , 'Num']]

In [11]:
categorical = categorical.drop( columns = ['HomePlanet_0' , 'Destination_0' , 'Deck_0' , 'Side_0'] , axis = 1)

In [12]:
numerical = numerical.astype('int')

X_train_f = categorical.join(numerical)

In [13]:
X_train_f = X_train_f.join(name_df)
X_train_f = X_train_f.rename( columns = { 0 : 'Name'  })

In [14]:


y_train = y_train.astype('int')

In [15]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

scaler = StandardScaler()

names = X_train_f.columns 
X_train = scaler.fit_transform(X_train_f)

X_train = pd.DataFrame( X_train , columns=names)

In [18]:
X_train = X_train.join(y_train)

ValueError: ignored

In [21]:
X_train

,HomePlanet_Earth,HomePlanet_Europa,HomePlanet_Mars,Destination_55 Cancri e,Destination_PSO J318.5-22,Destination_TRAPPIST-1e,Deck_A,Deck_B,Deck_C,Deck_D,...,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Group,Number_in_group,Num,Name,Transported
0,-1.060617,1.754795,-0.503664,-0.511013,-0.317487,0.685313,-0.174191,3.187347,-0.30661,-0.241218,...,-0.333105,-0.281027,-0.283579,-0.270626,-0.263003,-1.734409,-0.491161,-1.141624,0.446353,0
1,0.942847,-0.569867,-0.503664,-0.511013,-0.317487,0.685313,-0.174191,-0.313741,-0.30661,-0.241218,...,-0.168073,-0.275387,-0.241771,0.217158,-0.224205,-1.734034,-0.491161,-1.141624,0.146306,1
2,-1.060617,1.754795,-0.503664,-0.511013,-0.317487,0.685313,5.740821,-0.313741,-0.30661,-0.241218,...,-0.268001,1.959998,-0.283579,5.695623,-0.219796,-1.733660,-0.491161,-1.141624,-1.471948,0
3,-1.060617,1.754795,-0.503664,-0.511013,-0.317487,0.685313,5.740821,-0.313741,-0.30661,-0.241218,...,-0.333105,0.523010,0.336851,2.687176,-0.092818,-1.733660,0.457443,-1.141624,1.205272,0
4,0.942847,-0.569867,-0.503664,-0.511013,-0.317487,0.685313,-0.174191,-0.313741,-0.30661,-0.241218,...,0.125652,-0.237159,-0.031059,0.231374,-0.261240,-1.733286,-0.491161,-1.139678,1.673345,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,-1.060617,1.754795,-0.503664,1.956897,-0.317487,-1.459188,5.740821,-0.313741,-0.30661,-0.241218,...,-0.333105,3.992336,-0.283579,1.189173,-0.197751,1.738236,-0.491161,-0.950907,-0.244955,0
8689,0.942847,-0.569867,-0.503664,-0.511013,3.149739,-1.459188,-0.174191,-0.313741,-0.30661,-0.241218,...,-0.333105,-0.281027,-0.283579,-0.270626,-0.263003,1.738984,-0.491161,1.775567,0.257523,0
8690,0.942847,-0.569867,-0.503664,-0.511013,-0.317487,0.685313,-0.174191,-0.313741,-0.30661,-0.241218,...,-0.333105,-0.281027,2.846999,-0.269737,-0.263003,1.739359,-0.491161,1.777513,-0.453788,1
8691,-1.060617,1.754795,-0.503664,1.956897,-0.317487,-1.459188,-0.174191,-0.313741,-0.30661,-0.241218,...,-0.333105,0.376365,-0.283579,0.043013,2.589576,1.739733,-0.491161,0.041600,-1.016276,0
8692,-1.060617,1.754795,-0.503664,-0.511013,-0.317487,0.685313,-0.174191,-0.313741,-0.30661,-0.241218,...,-0.142335,2.656871,-0.283579,-0.270626,-0.252422,1.739733,0.457443,0.041600,0.897624,1

In [101]:
import torch

train_list = []

for i, row in X_train.iterrows():
    row = row.tolist()
    label = row[-1]
    label = int(label)
    
    info = row[:-1]

    info = torch.Tensor(info)
    
    tpl = ( info , label )
    
    train_list.append(tpl)

1

In [102]:
batch_size = 16
dataloader = torch.utils.data.DataLoader( train_list  ,
                                         batch_size = batch_size ,
                                         shuffle = True , 
                                         num_workers= 0 , 
                                         drop_last = True 
                                         )

In [116]:
from torch import nn 

class Neural_network(nn.Module):
  #Arch и ее блоки
  def __init__(self):
        # импортим свойства nn.Module
        super().__init__() 
        
        self.flat = nn.Flatten()
        self.linear1 = nn.Linear(28 , 512)
        self.linear2 = nn.Linear(512 , 256)
        self.linear3 = nn.Linear(256 , 128)
        self.linear4 = nn.Linear(128, 64)
        self.linear5 = nn.Linear(64 , 128)
        self.linear6 = nn.Linear( 128 , 128)
        self.linear7 = nn.Linear( 128 , 2 )

        self.act = nn.LeakyReLU()
        
       # self.model = nn.Sequential( linear1 , act , linear2)
   # как будут перемещаться тензоры в нейронной сети      
  def forward(self, x): # x - tensor 
    out = self.flat(x)
    out = self.linear1(out)
    out = self.act(out)
    out = self.linear2(out)
    out = self.act(out)
    out = self.linear3(out)
    out = self.act(out)
    out = self.linear4(out)
    out = self.act(out)
    out = self.linear5(out)
    out = self.act(out)
    out = self.linear6(out)
    out = self.act(out)
    out = self.linear7(out)

    return out

In [112]:
model = Neural_network()
loss_fn =  torch.nn.CrossEntropyLoss()
optimizer = torch.optim.AdamW( model.parameters() , lr = 4e-3 )

In [105]:
def accuracy(pred , label) :
    
    answer = F.softmax(pred.detach()).numpy().argmax(1)  == label.numpy().argmax(1)
    
    return answer.mean()

In [106]:
for sample , label in dataloader :
  print(sample)
  print(label)
  break

tensor([[ 9.4285e-01, -5.6987e-01, -5.0366e-01, -5.1101e-01, -3.1749e-01,
          6.8531e-01, -1.7419e-01, -3.1374e-01, -3.0661e-01, -2.4122e-01,
         -3.3476e-01, -6.8821e-01,  1.5482e+00, -2.3990e-02,  1.0329e+00,
         -9.8663e-01,  1.3647e+00, -1.6923e+00, -1.5306e-01, -3.3310e-01,
         -2.8103e-01, -2.8358e-01, -2.7063e-01, -2.6300e-01,  1.0194e+00,
          4.5744e-01,  1.1567e+00, -1.0933e-01],
        [-1.0606e+00,  1.7548e+00, -5.0366e-01, -5.1101e-01, -3.1749e-01,
          6.8531e-01, -1.7419e-01,  3.1873e+00, -3.0661e-01, -2.4122e-01,
         -3.3476e-01, -6.8821e-01, -6.4590e-01, -2.3990e-02,  1.0329e+00,
         -9.8663e-01, -7.3277e-01, -8.2048e-01, -1.5306e-01, -3.3310e-01,
         -2.5283e-01, -2.8023e-01,  4.3344e+00, -1.1310e-01, -1.5584e+00,
         -4.9116e-01, -1.0988e+00, -1.3307e+00],
        [-1.0606e+00,  1.7548e+00, -5.0366e-01, -5.1101e-01, -3.1749e-01,
          6.8531e-01, -1.7419e-01,  3.1873e+00, -3.0661e-01, -2.4122e-01,
         -3.3476e-01, -6.8821e-01, -6.4590e-01, -2.3990e-02, -9.6818e-01,
          1.0136e+00, -7.3277e-01, -6.1929e-01, -1.5306e-01, -3.3310e-01,
          2.5604e+00, -2.8358e-01,  2.7758e-01,  7.5634e-01,  1.1646e+00,
         -4.9116e-01, -5.6169e-01,  1.6529e+00],
        [ 9.4285e-01, -5.6987e-01, -5.0366e-01, -5.1101e-01, -3.1749e-01,
          6.8531e-01, -1.7419e-01, -3.1374e-01, -3.0661e-01, -2.4122e-01,
         -3.3476e-01, -6.8821e-01,  1.5482e+00, -2.3990e-02,  1.0329e+00,
         -9.8663e-01, -7.3277e-01, -1.6252e+00, -1.5306e-01, -3.3310e-01,
         -2.8103e-01, -2.8358e-01, -2.7063e-01, -2.6300e-01,  4.0459e-01,
         -4.9116e-01,  6.4100e-01,  1.8631e-01],
        [ 9.4285e-01, -5.6987e-01, -5.0366e-01, -5.1101e-01, -3.1749e-01,
          6.8531e-01, -1.7419e-01, -3.1374e-01, -3.0661e-01, -2.4122e-01,
         -3.3476e-01, -6.8821e-01,  1.5482e+00, -2.3990e-02, -9.6818e-01,
          1.0136e+00, -7.3277e-01, -1.8935e+00, -1.5306e-01, -3.3310e-01,
         -2.8103e-01, -2.8358e-01, -2.7063e-01, -2.6300e-01, -6.3252e-01,
          2.3547e+00, -2.2891e-01,  1.3885e+00],
        [ 9.4285e-01, -5.6987e-01, -5.0366e-01, -5.1101e-01, -3.1749e-01,
          6.8531e-01, -1.7419e-01, -3.1374e-01, -3.0661e-01, -2.4122e-01,
         -3.3476e-01, -6.8821e-01,  1.5482e+00, -2.3990e-02, -9.6818e-01,
          1.0136e+00, -7.3277e-01, -1.8264e+00, -1.5306e-01, -3.3310e-01,
         -2.8103e-01, -2.8358e-01, -2.7063e-01, -2.6300e-01, -5.3855e-01,
         -4.9116e-01, -1.5885e-01,  9.2803e-01],
        [-1.0606e+00,  1.7548e+00, -5.0366e-01, -5.1101e-01, -3.1749e-01,
          6.8531e-01, -1.7419e-01, -3.1374e-01,  3.2615e+00, -2.4122e-01,
         -3.3476e-01, -6.8821e-01, -6.4590e-01, -2.3990e-02, -9.6818e-01,
          1.0136e+00, -7.3277e-01,  1.4597e+00, -1.5306e-01,  5.2340e+00,
          2.0904e-01, -2.8358e-01, -2.6529e-01,  7.6692e-01, -1.0732e+00,
          4.5744e-01, -1.0151e+00, -7.8384e-01],
        [-1.0606e+00,  1.7548e+00, -5.0366e-01, -5.1101e-01, -3.1749e-01,
          6.8531e-01, -1.7419e-01,  3.1873e+00, -3.0661e-01, -2.4122e-01,
         -3.3476e-01, -6.8821e-01, -6.4590e-01, -2.3990e-02,  1.0329e+00,
         -9.8663e-01, -7.3277e-01,  6.5492e-01, -1.5306e-01, -3.3310e-01,
         -2.8103e-01, -2.8358e-01, -2.7063e-01, -2.6300e-01,  2.5969e-01,
         -4.9116e-01, -7.8549e-01, -3.9058e-01],
        [ 9.4285e-01, -5.6987e-01, -5.0366e-01, -5.1101e-01, -3.1749e-01,
          6.8531e-01, -1.7419e-01, -3.1374e-01, -3.0661e-01, -2.4122e-01,
         -3.3476e-01,  1.4530e+00, -6.4590e-01, -2.3990e-02, -9.6818e-01,
          1.0136e+00, -7.3277e-01,  1.8548e-01, -1.5306e-01, -3.3310e-01,
         -1.7261e-01,  4.0040e-01, -1.8000e-01, -2.2509e-01,  1.6379e+00,
         -4.9116e-01,  2.2543e+00,  1.0088e+00],
        [ 9.4285e-01, -5.6987e-01, -5.0366e-01, -5.1101e-01, -3.1749e-01,
          6.8531e-01, -1.7419e-01, -3.1374e-01, -3.0661e-01, -2.4122e-01,
         -3.3476e-01,  1.4530e+00, -6.4590e-01, -2.3990e-02, -9.6818e-01,
          1.0136e+00, -7.3277e-01,  1.8548e-01, -1.5306e-01,  1.2748e+00,
         -2.8103e-01,  1.0576e+00, -2.0754e-01, -2.6300e-01, -9.8859e-01,
         -4.9116e-01, -4.0211e-01,  3.7994e-01],
        [-1.0606e+00,  1.7548e+00, -5.0366e-01, -5.1101e-01, -3.1749e-01,
          6.8531e-01, -1.7419e-01, -3.1374e-01,  3.2615e+00, -2.4122e-01,
         -3.3476e-01, -6.8821e-01, -6.4590e-01, -2.3990e-02,  1.0329e+00,
         -9.8663e-01, -7.3277e-01, -1.8935e+00, -1.5306e-01, -3.3310e-01,
          2.5491e+00, -2.8358e-01,  5.2087e+00,  4.4175e+00, -1.4748e-02,
          2.3547e+00, -8.6139e-01, -3.8938e-01],
        [-1.0606e+00,  1.7548e+00, -5.0366e-01, -5.1101e-01, -3.1749e-01,
          6.8531e-01,  5.7408e+00, -3.1374e-01, -3.0661e-01, -2.4122e-01,
         -3.3476e-01, -6.8821e-01, -6.4590e-01, -2.3990e-02, -9.6818e-01,
          1.0136e+00, -7.3277e-01,  1.7279e+00, -1.5306e-01, -3.3310e-01,
          4.7601e-01, -2.8358e-01, -2.6796e-01,  2.9869e-01, -1.6985e+00,
         -4.9116e-01, -1.1377e+00, -1.5892e+00],
        [ 9.4285e-01, -5.6987e-01, -5.0366e-01, -5.1101e-01, -3.1749e-01,
          6.8531e-01, -1.7419e-01, -3.1374e-01, -3.0661e-01, -2.4122e-01,
         -3.3476e-01, -6.8821e-01,  1.5482e+00, -2.3990e-02, -9.6818e-01,
          1.0136e+00, -7.3277e-01, -1.5582e+00, -1.5306e-01, -3.3310e-01,
         -2.8103e-01, -2.8358e-01, -2.7063e-01, -2.6300e-01,  5.2290e-01,
         -4.9116e-01,  7.6749e-01, -1.3587e+00],
        [ 9.4285e-01, -5.6987e-01, -5.0366e-01,  1.9569e+00, -3.1749e-01,
         -1.4592e+00, -1.7419e-01, -3.1374e-01, -3.0661e-01, -2.4122e-01,
         -3.3476e-01,  1.4530e+00, -6.4590e-01, -2.3990e-02,  1.0329e+00,
         -9.8663e-01, -7.3277e-01, -2.8397e-01, -1.5306e-01,  8.5694e-01,
         -2.8103e-01, -2.8358e-01,  3.9193e-03, -2.6300e-01,  1.0583e+00,
         -4.9116e-01,  1.8612e+00,  3.0593e-01],
        [ 9.4285e-01, -5.6987e-01, -5.0366e-01, -5.1101e-01,  3.1497e+00,
         -1.4592e+00, -1.7419e-01, -3.1374e-01, -3.0661e-01, -2.4122e-01,
         -3.3476e-01, -6.8821e-01,  1.5482e+00, -2.3990e-02,  1.0329e+00,
         -9.8663e-01, -7.3277e-01, -6.8635e-01, -1.5306e-01, -3.3310e-01,
         -2.8103e-01,  2.5928e+00, -2.6974e-01, -2.6300e-01,  6.6218e-01,
          2.3547e+00,  8.6674e-01, -4.5899e-01],
        [ 9.4285e-01, -5.6987e-01, -5.0366e-01,  1.9569e+00, -3.1749e-01,
         -1.4592e+00, -1.7419e-01, -3.1374e-01, -3.0661e-01, -2.4122e-01,
         -3.3476e-01, -6.8821e-01,  1.5482e+00, -2.3990e-02,  1.0329e+00,
         -9.8663e-01, -7.3277e-01, -4.8516e-01, -1.5306e-01, -3.3310e-01,
         -2.8103e-01,  1.2349e+00, -2.2709e-01, -2.6300e-01, -1.5034e+00,
         -4.9116e-01, -9.5675e-01,  8.4642e-01]])
tensor([1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1])

In [46]:
for s , l in dataloader :
  print(s[0])
  print(l[0])
  break

tensor([ 0.9428, -0.5699, -0.5037, -0.5110,  3.1497, -1.4592, -0.1742, -0.3137,
        -0.3066, -0.2412, -0.3348, -0.6882,  1.5482, -0.0240,  1.0329, -0.9866,
         1.3647, -0.0828, -0.1531, -0.3331, -0.2810, -0.2836, -0.2706, -0.2630,
        -0.9212, -0.4912, -0.4566,  1.5585])
tensor(1., dtype=torch.float64)

In [135]:
epochs = 20 

for epoch in range(epochs):

  loss_val = 0 
  acc_val = 0 

  for sample , label in (pbar := tqdm(dataloader)) : # просто запомнить визуализация
    optimizer.zero_grad() #  Обнови градиенты (в нуль их так как новые будем считать, чтобы они не наслаивались)
     # 1 - > [ 1, 0 ... 0 ]
    label = nn.functional.one_hot( label , 2 ).float()
    
    pred = model(sample) # vector вероятностей [ 0 , 0 , 0 , 1 ... 0 ] для тройки
    
    loss = loss_fn(pred , label) # мы сделали pred & label одного вида чтобы их сравнить


    loss.backward() # считает градиенты

    loss_item = loss.item()
    loss_val += loss_item

    acc_current = accuracy(pred , label)
    acc_val  += acc_current
    optimizer.step() # шагаем оптимайзером , считаем веса 

  
   # .4 - 4 знака после запятой .4f - norm forma , .4e - nauchnaya forma 
    pbar.set_description(f'loss : {loss_item:.4f}\taccuracy : {acc_current:.3f}')  # ПРОСТО ЗАПОМНИТЬ прогресс лосса 
  print( f'epoch {epoch + 1 }' , f' loss_val : {loss_val / len(dataloader) }'
  , f'acc_val : {acc_val / len(dataloader)}')

  0%|          | 0/543 [00:00<?, ?it/s]<ipython-input-105-758b855bc9b3>:3: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  answer = F.softmax(pred.detach()).numpy().argmax(1)  == label.numpy().argmax(1)
loss : 0.4649	accuracy : 0.688: 100%|██████████| 543/543 [00:03<00:00, 152.82it/s]

epoch 1  loss_val : 0.3516010641777274 acc_val : 0.8263121546961326

loss : 0.2699	accuracy : 0.938: 100%|██████████| 543/543 [00:02<00:00, 186.47it/s]

epoch 2  loss_val : 0.3455559148094711 acc_val : 0.8340239410681399

loss : 0.3815	accuracy : 0.875: 100%|██████████| 543/543 [00:02<00:00, 202.12it/s]

epoch 3  loss_val : 0.3519831739613035 acc_val : 0.8309162062615101

loss : 0.3833	accuracy : 0.812: 100%|██████████| 543/543 [00:02<00:00, 185.82it/s]

epoch 4  loss_val : 0.3488228144621542 acc_val : 0.8322974217311234

loss : 0.5194	accuracy : 0.750: 100%|██████████| 543/543 [00:02<00:00, 186.20it/s]

epoch 5  loss_val : 0.3465285235621433 acc_val : 0.8351749539594844

loss : 0.4227	accuracy : 0.812: 100%|██████████| 543/543 [00:03<00:00, 171.72it/s]

epoch 6  loss_val : 0.34464407210027315 acc_val : 0.8398941068139963

loss : 0.3503	accuracy : 0.812: 100%|██████████| 543/543 [00:03<00:00, 173.24it/s]

epoch 7  loss_val : 0.3487201595805846 acc_val : 0.83195211786372

loss : 0.2701	accuracy : 0.875: 100%|██████████| 543/543 [00:02<00:00, 190.85it/s]

epoch 8  loss_val : 0.34268752914299405 acc_val : 0.8327578268876611

loss : 0.3278	accuracy : 0.875: 100%|██████████| 543/543 [00:02<00:00, 181.10it/s]

epoch 9  loss_val : 0.3460009983203907 acc_val : 0.8342541436464088

loss : 0.1452	accuracy : 0.938: 100%|██████████| 543/543 [00:03<00:00, 164.26it/s]

epoch 10  loss_val : 0.34820124279179404 acc_val : 0.8359806629834254

loss : 0.3691	accuracy : 0.812: 100%|██████████| 543/543 [00:03<00:00, 149.66it/s]

epoch 11  loss_val : 0.3430929362746453 acc_val : 0.8344843462246777

loss : 0.6115	accuracy : 0.625: 100%|██████████| 543/543 [00:03<00:00, 145.46it/s]

epoch 12  loss_val : 0.3440510150230392 acc_val : 0.8322974217311234

loss : 0.3937	accuracy : 0.812: 100%|██████████| 543/543 [00:03<00:00, 176.32it/s]

epoch 13  loss_val : 0.34619440189108225 acc_val : 0.8355202578268877

loss : 0.1594	accuracy : 1.000: 100%|██████████| 543/543 [00:02<00:00, 186.89it/s]

epoch 14  loss_val : 0.3411946729868376 acc_val : 0.8351749539594844

loss : 0.1668	accuracy : 0.938: 100%|██████████| 543/543 [00:03<00:00, 178.05it/s]

epoch 15  loss_val : 0.3394916052509847 acc_val : 0.8345994475138122

loss : 0.4985	accuracy : 0.750: 100%|██████████| 543/543 [00:02<00:00, 183.17it/s]

epoch 16  loss_val : 0.338466701572881 acc_val : 0.8360957642725598

loss : 0.4224	accuracy : 0.812: 100%|██████████| 543/543 [00:02<00:00, 201.32it/s]

epoch 17  loss_val : 0.3394005903716904 acc_val : 0.8371316758747698

loss : 0.2288	accuracy : 0.875: 100%|██████████| 543/543 [00:02<00:00, 197.82it/s]

epoch 18  loss_val : 0.33739739958999565 acc_val : 0.8406998158379374

loss : 0.1259	accuracy : 0.938: 100%|██████████| 543/543 [00:02<00:00, 185.73it/s]

epoch 19  loss_val : 0.34396038509040905 acc_val : 0.8426565377532228

loss : 0.4467	accuracy : 0.938: 100%|██████████| 543/543 [00:02<00:00, 188.32it/s]

epoch 20  loss_val : 0.3368312655150561 acc_val : 0.841390423572744

In [119]:

passenger_id = X_test['PassengerId'] # оставить на этом месте

In [120]:
# test
name = X_test['Name']
X_test = X_test.drop(columns =['Name'] , axis = 1 )

labelencoder = LabelEncoder()
name = name.astype('str')
name = labelencoder.fit_transform(name)
name_df = pd.DataFrame(name)

passengers = []
ids = []
Pass_id_dict = {}
for i in X_test.PassengerId :
  split_i = i.split('_')
  split_i[1] = int(split_i[1])
  
  passengers.append(split_i[0])
  ids.append(split_i[1]) 
X_test['Group'] = passengers
X_test['Number_in_group'] = ids

X_test = X_test.drop( columns = ['PassengerId'] , axis = 1 )
X_test.head(20)


import numpy as np
deck =[]
num=[]
side=[]
for i in X_test.Cabin :
  if i != 0 :
    
    split_i = i.split('/')
    deck.append(split_i[0])
    num.append(int(split_i[1]))
    side.append(split_i[2])
  if i == 0 :
    deck.append(0)
    num.append(0)
    side.append(0)



  
X_test['Deck'] = deck
X_test['Num'] = num
X_test['Side'] = side
X_test = X_test.drop( columns = ['Cabin' ] , axis = 1 )

categorical = X_test[['HomePlanet' , 'Destination'  , 'Deck' , 'Side']]
categorical = pd.get_dummies(categorical)




numerical = X_test[['CryoSleep' , 'Age' , 'VIP' , 'RoomService' , 'FoodCourt' , 'ShoppingMall' , 'Spa' , 'VRDeck' , 'Group' , 'Number_in_group' , 'Num']]
categorical = categorical.drop( columns = ['HomePlanet_0' , 'Destination_0' , 'Deck_0' , 'Side_0'] , axis = 1)
numerical = numerical.astype('int')

X_test_f = categorical.join(numerical)

X_test_f = X_test_f.join(name_df)
X_test_f = X_test_f.rename( columns = { 0 : 'Name'  })
X_test_f

,HomePlanet_Earth,HomePlanet_Europa,HomePlanet_Mars,Destination_55 Cancri e,Destination_PSO J318.5-22,Destination_TRAPPIST-1e,Deck_A,Deck_B,Deck_C,Deck_D,...,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Group,Number_in_group,Num,Name
0,1,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,13,1,3,2913
1,1,0,0,0,0,1,0,0,0,0,...,0,0,9,0,2823,0,18,1,4,2407
2,0,1,0,1,0,0,0,0,1,0,...,0,0,0,0,0,0,19,1,0,3377
3,0,1,0,0,0,1,0,0,1,0,...,0,0,6652,0,181,585,21,1,1,2712
4,1,0,0,0,0,1,0,0,0,0,...,0,10,0,635,0,0,23,1,5,669
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4272,1,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,9266,2,1496,2106
4273,1,0,0,0,0,1,0,0,0,0,...,0,0,847,17,10,144,9269,1,0,2655
4274,0,0,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,9271,1,296,2086
4275,0,1,0,0,0,0,0,0,0,1,...,0,0,2680,0,0,523,9273,1,297,2328
4276,1,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,9277,1,1498,2440

In [121]:


scaler = StandardScaler()

names = X_test_f.columns 
X_test = scaler.fit_transform(X_test_f)

X_test = pd.DataFrame( X_test , columns=names)

In [122]:
X_test

,HomePlanet_Earth,HomePlanet_Europa,HomePlanet_Mars,Destination_55 Cancri e,Destination_PSO J318.5-22,Destination_TRAPPIST-1e,Deck_A,Deck_B,Deck_C,Deck_D,...,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Group,Number_in_group,Num,Name
0,0.943382,-0.553131,-0.525314,-0.494734,-0.315862,0.668497,-0.153136,-0.30408,-0.300857,-0.244898,...,-0.132689,-0.357339,-0.283840,-0.312173,-0.267841,-0.246712,-1.703425,-0.489847,-1.146527,0.708477
1,0.943382,-0.553131,-0.525314,-0.494734,-0.315862,0.668497,-0.153136,-0.30408,-0.300857,-0.244898,...,-0.132689,-0.357339,-0.277879,-0.312173,2.287504,-0.246712,-1.701584,-0.489847,-1.144593,0.297314
2,-1.060016,1.807889,-0.525314,2.021290,-0.315862,-1.495894,-0.153136,-0.30408,3.323836,-0.244898,...,-0.132689,-0.357339,-0.283840,-0.312173,-0.267841,-0.246712,-1.701215,-0.489847,-1.152328,1.085511
3,-1.060016,1.807889,-0.525314,-0.494734,-0.315862,0.668497,-0.153136,-0.30408,3.323836,-0.244898,...,-0.132689,-0.357339,4.121518,-0.312173,-0.104002,0.226648,-1.700479,-0.489847,-1.150395,0.545149
4,0.943382,-0.553131,-0.525314,-0.494734,-0.315862,0.668497,-0.153136,-0.30408,-0.300857,-0.244898,...,-0.132689,-0.340723,-0.283840,0.832122,-0.267841,-0.246712,-1.699743,-0.489847,-1.142660,-1.114938
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4272,0.943382,-0.553131,-0.525314,-0.494734,-0.315862,0.668497,-0.153136,-0.30408,-0.300857,-0.244898,...,-0.132689,-0.357339,-0.283840,-0.312173,-0.267841,-0.246712,1.703574,0.492373,1.740519,0.052730
4273,0.943382,-0.553131,-0.525314,-0.494734,-0.315862,0.668497,-0.153136,-0.30408,-0.300857,-0.244898,...,-0.132689,-0.357339,0.277095,-0.281538,-0.258790,-0.130193,1.704679,-0.489847,-1.152328,0.498833
4274,-1.060016,-0.553131,1.903624,2.021290,-0.315862,-1.495894,-0.153136,-0.30408,-0.300857,4.083326,...,-0.132689,-0.357339,-0.283840,-0.312173,-0.267841,-0.246712,1.705415,-0.489847,-0.579947,0.036478
4275,-1.060016,1.807889,-0.525314,-0.494734,-0.315862,-1.495894,-0.153136,-0.30408,-0.300857,4.083326,...,-0.132689,-0.357339,1.491019,-0.312173,-0.267841,0.176479,1.706152,-0.489847,-0.578013,0.233121
4276,0.943382,-0.553131,-0.525314,-0.494734,3.165943,-1.495894,-0.153136,-0.30408,-0.300857,-0.244898,...,-0.132689,-0.357339,-0.283840,-0.312173,-0.267841,-0.246712,1.707625,-0.489847,1.744386,0.324129

In [125]:
#NN
test_ds = []
for i, row in X_test.iterrows():
    row = row.tolist()
    
    
    

    
    
    

    
    
    
    row = torch.Tensor(row)
    
    test_ds.append(row)

In [132]:
len(test_ds[0])
test_ds[0]

tensor([ 0.9434, -0.5531, -0.5253, -0.4947, -0.3159,  0.6685, -0.1531, -0.3041,
        -0.3009, -0.2449, -0.3416, -0.7143,  1.5811, -0.0375, -0.9748,  1.0215,
         1.3304, -0.0717, -0.1327, -0.3573, -0.2838, -0.3122, -0.2678, -0.2467,
        -1.7034, -0.4898, -1.1465,  0.7085])

In [152]:
batch_size = 16
test_dataloader = torch.utils.data.DataLoader( test_ds  ,
                                         batch_size = batch_size ,
                                         shuffle = False  , 
                                         num_workers= 0 , 
                                         
                                         )

predictions_list = []
for i in test_dataloader :
  pred = model(i)
  
  for j in pred :
    j = j.detach()
    j = F.softmax(j)
    j = j.numpy()
    j = j.argmax()
    predictions_list.append(j)

<ipython-input-152-f668f555226b>:15: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  j = F.softmax(j)

In [153]:
len(predictions_list )

4277

In [154]:
predictions_list

[1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 ...]

In [156]:
result = pd.DataFrame({'PassengerId' : passenger_id , 'Transported' : predictions_list })

In [158]:
result['Transported'] = result['Transported'].astype(bool)

In [159]:
result

     PassengerId  Transported
0        0013_01         True
1        0018_01        False
2        0019_01         True
3        0021_01         True
4        0023_01         True
...          ...          ...
4272     9266_02        False
4273     9269_01        False
4274     9271_01         True
4275     9273_01         True
4276     9277_01        False

[4277 rows x 2 columns]

In [160]:
result.to_csv ('/content/neuralnetwork.csv', index= False )